steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['clean', 'build']

- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/server:$SHORT_SHA
  - .

#- name: 'gcr.io/cloud-builders/docker'
#  args: ["push", "gcr.io/$PROJECT_ID/server:$SHORT_SHA"]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - server
  - server=gcr.io/$PROJECT_ID/server:$SHORT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

images:
- 'gcr.io/$PROJECT_ID/server:$SHORT_SHA'